# Generated by Django 4.1.3 on 2023-02-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="data", options={"managed": False},),
    ]
