# Generated by Django 4.1.3 on 2023-02-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_buildingattributeinformationmodel_building"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BuildingAttributeInformationModel",
            new_name="BuildingAttributeInformationModels",
        ),
    ]
