# Generated by Django 4.1.3 on 2023-02-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_alter_data_options"),
    ]

    operations = [
        migrations.AlterModelTable(name="data", table="data",),
    ]
